### ISSUE TITLE
No Chrome installations found

### ISSUE THREAD

**Issue by DenisBalan** [femtopixel/docker-google-lighthouse#17]
run
```
docker run --rm --name lighthouse -it -v /path/to/your/report:/home/chrome/reports femtopixel/google-lighthouse http://www.google.com --output json
```
output
```
Runtime error encountered: No Chrome installations found.
Error
    at new LauncherError (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:35:22)
    at new ChromeNotInstalledError (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:66:9)
    at Launcher.<anonymous> (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:146:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:9:58)
```

**Comment by jaymoulin** [comment]
Thank you for reporting this. You issue doesn't match the issue template preventing me (and users) to answer your question. Your issue will be reopened when required information are provided. Thank you for your understanding
