### ISSUE TITLE
BUG: Unable to locate audit

### ISSUE THREAD

**Issue by egemon** [femtopixel/docker-google-lighthouse#18]
**Output of `docker inspect lighthouse --format='{{index .Config.Labels.version}}'`:**

```
wait a sec
```

**Description**

Jun 25, 2020 9:31 PM - jenkins build running lighthouse inpsection is working
Jun 26, 2020 2:32 PM - it is not working with error below

**Command line I used to start the container**
Jenkins 

**Steps to reproduce the issue:**
1. build dockerfile based on this image from this repo
2. run inpsection

**Describe the results you received:**
Errors below

**Describe the results you expected:**
Reports are generated

**Additional information you deem important (e.g. issue happens only occasionally):**
I think it has smth to do with release of new verions of lighthouse. 
Also I am rebuilding docker image on each build to grap last code that runs lighthouse
with lighthouse version 6.1.0

**Provide some logs (`docker logs lighthouse`)**

<details>
<pre>
checkPerformance started
17:33:16 
17:33:16 launchLighthouse started
17:33:16 
17:33:16 cmd lighthouse  --output=json --output=html --output-path=stdout --chrome-flags="--headless --disable-gpu --no-sandbox" --config-path=./configs/default.json https://auto-development.weplay.space
17:33:16 
17:33:16 lighthouse started
17:33:16 
17:33:18 Fri, 26 Jun 2020 14:33:18 GMT ChromeLauncher Waiting for browser.
17:33:18 
17:33:18 
17:33:18 Fri, 26 Jun 2020 14:33:18 GMT ChromeLauncher Waiting for browser...
17:33:18 
17:33:18 
17:33:18 Fri, 26 Jun 2020 14:33:18 GMT ChromeLauncher Waiting for browser.....
17:33:18 
17:33:18 
17:33:19 Fri, 26 Jun 2020 14:33:19 GMT ChromeLauncher Waiting for browser.......
17:33:19 
17:33:19 
17:33:19 Fri, 26 Jun 2020 14:33:19 GMT ChromeLauncher Waiting for browser.........
17:33:19 
17:33:19 
17:33:19 Fri, 26 Jun 2020 14:33:19 GMT ChromeLauncher Waiting for browser.........✓
17:33:19 
17:33:19 
17:33:19 Fri, 26 Jun 2020 14:33:19 GMT ChromeLauncher Killing Chrome instance 33
17:33:19 
17:33:19 
17:33:19 Runtime error encountered: Unable to locate audit: `time-to-first-byte`.
17:33:19      Tried to require() from these locations:
17:33:19        /usr/lib/node_modules/lighthouse/lighthouse-core/config
17:33:19        /home/chrome/time-to-first-byte
17:33:19        /home/chrome/configs/time-to-first-byte
17:33:19 
17:33:19 
17:33:19 Error: Unable to locate audit: `time-to-first-byte`.
17:33:19      Tried to require() from these locations:
17:33:19        /usr/lib/node_modules/lighthouse/lighthouse-core/config
17:33:19        /home/chrome/time-to-first-byte
17:33:19        /home/chrome/configs/time-to-first-byte
17:33:19     at resolveModule (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config-helpers.js:212:9)
17:33:19     at /usr/lib/node_modules/lighthouse/lighthouse-core/config/config-helpers.js:147:32
17:33:19     at Array.map (<anonymous>)
17:33:19     at requireAudits (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config-helpers.js:131:37)
17:33:19     at Function.requireAudits (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config.js:754:24)
17:33:19     at new Config (/usr/lib/node_modules/lighthouse/lighthouse-core/config/config.js:347:26)
17:33:19     at generateConfig (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:60:10)
17:33:19     at lighthouse (/usr/lib/node_modules/lighthouse/lighthouse-core/index.js:43:18)
17:33:19     at runLighthouse (/usr/lib/node_modules/lighthouse/lighthouse-cli/run.js:209:32)
17:33:19     at processTicksAndRejections (internal/process/task_queues.js:97:5)
17:33:19 
17:33:19 
</pre>
</details>

**Comment by egemon** [comment]
Issues was in fact that I was using configs, generated by previouse verions of lighthouse, while docker image has been updated to new version with breaking change of lighthouse major update. 
Probably I should use docker images with semver approach as any other package manager, not just. 
Hope this will be helpful for smbd here.
